# Generated by Django 5.1 on 2024-08-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0002_classe_cours_curriculum_delete_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
            ],
        ),
    ]
