# Generated by Django 5.1 on 2024-08-22 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0003_salle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='intitule_cours',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='EdT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creneau_horaire', models.IntegerField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edt.classe')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edt.cours')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edt.salle')),
            ],
        ),
    ]
