# Generated by Django 5.1.3 on 2024-11-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edt', '0004_alter_cours_intitule_cours_edt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edt',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='edt',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='edt',
            name='salle',
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
        migrations.DeleteModel(
            name='EdT',
        ),
    ]
